// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: Battle.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Messages.Battle
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Operation : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public OperationType operation_type { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"user_id")]
        public int UserId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"battle_user_id")]
        public int BattleUserId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"frame_id")]
        public int FrameId { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public Direction direction { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class Direction : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"x")]
            public float X { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"y")]
            public float Y { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public enum OperationType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"IDLE")]
            Idle = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"MOVE")]
            Move = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"ATTACK")]
            Attack = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"SKILL_1")]
            Skill1 = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"SKILL_2")]
            Skill2 = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"SKILL_3")]
            Skill3 = 5,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BattleUserInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"user_id")]
        public int UserId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"battle_user_id")]
        public int BattleUserId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"role_id")]
        public int RoleId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BattleReadyRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"battle_id")]
        public int BattleId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"battle_user_id")]
        public int BattleUserId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OperationRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"battle_id")]
        public int BattleId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"operation")]
        public Operation Operation { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DeltaFramesRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"battle_id")]
        public int BattleId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"frames", IsPacked = true)]
        public int[] Frames { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GameOverRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"battle_user_id")]
        public int BattleUserId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EnterBattleResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"random_seed")]
        public int RandomSeed { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"battle_id")]
        public int BattleId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"battle_user_infos")]
        public global::System.Collections.Generic.List<BattleUserInfo> BattleUserInfos { get; } = new global::System.Collections.Generic.List<BattleUserInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BattleStartResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OperationsResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"frame_id")]
        public int FrameId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"operations")]
        public global::System.Collections.Generic.List<Operation> Operations { get; } = new global::System.Collections.Generic.List<Operation>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DeltaFramesResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"delta_frames")]
        public global::System.Collections.Generic.List<OperationsResponse> DeltaFrames { get; } = new global::System.Collections.Generic.List<OperationsResponse>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GameOverResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
